# Generated by Django 3.2.8 on 2021-11-11 21:15

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True, null=True, upload_to=authentication.models),
        ),
    ]
