# Generated by Django 3.2.8 on 2021-11-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
        migrations.AlterField(
            model_name='user',
            name='lng',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=23),
        ),
    ]
