# Generated by Django 3.2.8 on 2021-11-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20211103_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
